name: test-and-publish

on:
  push:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        environment: [ubuntu-24.04, windows-2022, macos-14]
        include:
          - environment: ubuntu-24.04
            publish-runtime-id: linux-x64
          - environment: windows-2022
            publish-runtime-id: win-x64
          - environment: macos-14
            publish-runtime-id: osx-x64

    runs-on: ${{ matrix.environment }}

    steps:

    - name: Avoid git mutating files on checkout
      run: |
        git config --global core.autocrlf false

    - uses: actions/checkout@v5

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Check installed dotnet
      run: dotnet --info

    - name: Clean package cache as a temporary workaround for https://github.com/actions/setup-dotnet/issues/155
      run: |
        dotnet clean ./implement/GitCore.UnitTests/GitCore.UnitTests.csproj && dotnet nuget locals all --clear
        dotnet clean ./implement/GitCore.IntegrationTests/GitCore.IntegrationTests.csproj && dotnet nuget locals all --clear

    - name: Check formatting in .NET source code
      run: |
        dotnet  format  ./implement/GitCore  --verify-no-changes  --verbosity detailed
        dotnet  format  ./implement/GitCore.UnitTests  --verify-no-changes  --verbosity detailed
        dotnet  format  ./implement/GitCore.IntegrationTests  --verify-no-changes  --verbosity detailed

    - name: Run GitCore unit tests
      run: |
        dotnet  run  --project=./implement/GitCore.UnitTests/GitCore.UnitTests.csproj  --  --report-xunit-trx  --diagnostic

    - name: Run integration tests
      run: |
        dotnet  run  --project=./implement/GitCore.IntegrationTests/GitCore.IntegrationTests.csproj  --  --report-xunit-trx  --diagnostic

    - name: Publish test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ github.sha }}-${{ matrix.environment }}
        # path: ./implement/GitCore.IntegrationTests/TestResults
        path: ./implement/**/TestResults

    - name: Compile Overview of Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        check_name: "Test Results Overview ${{ matrix.environment }}"
        files: |
          ./implement/**/TestResults/**/*.xml
          ./implement/**/TestResults/**/*.trx
          ./implement/**/TestResults/**/*.json


    - name: dotnet publish with separate assemblies
      run: dotnet publish -c Debug ./implement/GitCore --output ./publish-separate-assemblies

    - name: Publish artifacts with separate assemblies
      uses: actions/upload-artifact@v4
      with:
        name: GitCore-separate-assemblies-${{ github.sha }}-${{ matrix.publish-runtime-id }}
        path: ./publish-separate-assemblies

    - name: dotnet  build-server  shutdown
      run: dotnet  build-server  shutdown
